default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: thin_nginx_development

test:
  <<: *default
  database: thin_nginx_test

production:
  <<: *default
  database: thin_nginx_production
  username: root
  password:
